language: ruby
sudo: false
rvm:
- 2.3.4
addons:
  apt:
    packages:
      - aspell
      - aspell-en
      - aspell-pt-br
cache: bundler
before_script: ./check-spelling.sh
script: bundle exec rspec spec && bundle exec middleman build --verbose
deploy:
  skip_cleanup: true
  provider: pages
  repo: ember-brasil/ember-brasil.github.io
  target_branch: master
  github_token: $GITHUB_TOKEN
  local_dir: ./build
  on:
    branch: master
